[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[functions]
  # Increase the build timeout to 60 seconds (default is 10)
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

[build.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = ""
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = ""
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = ""
  NEXT_PUBLIC_FIREBASE_APP_ID = ""
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
